export const UNITS = {
  // Core Gameplay Balancing Parameters
  PLAYER_MAX_HP: 5,
  BOSS_MAX_HP: 80,
  BOSS_PHASE_2_HP_PCT: 0.70,
  BOSS_PHASE_3_HP_PCT: 0.40,

  // Player Kinematics
  PLAYER_MOVE_SPEED: 360,
  PLAYER_JUMP_FORCE: 544,
  PLAYER_WALL_SLIDE_SPEED: 96,
  PLAYER_DASH_SPEED: 1120,
  PLAYER_ACCEL: 12.0,
  PLAYER_DECEL: 16.0,

  // Boss Kinematics
  BOSS_PATROL_SPEED_BASE: 160,
  BOSS_LUNGE_SPEED_BASE: 960,
  BOSS_ACCEL: 6.0,
  BOSS_DECEL: 8.0,

  // Minion Kinematics
  MINION_ACCEL: 5.0,
  MINION_DECEL: 7.0,

  // Combat Damage
  PLAYER_MELEE_DAMAGE_BASE: 1,
  PLAYER_MELEE_DAMAGE_CLOSE: 5,
  PLAYER_FIREBALL_DAMAGE_LVL1: 1,
  PLAYER_FIREBALL_DAMAGE_LVL2: 3,
  HAZARD_SPIKE_DAMAGE: 1,
  ENEMY_CONTACT_DAMAGE: 1,
  BOSS_LUNGE_DAMAGE: 2,

  // Skill Cooldowns & Timings
  DASH_DURATION: 0.15,
  DASH_COOLDOWN: 0.50,
  HEAL_DURATION: 2.0,
  CHARGE_LVL1_TIME: 0.35,
  CHARGE_LVL2_TIME: 1.12,

  // World space coordinates (1 World Unit = 1 Pixel)
  WORLD_SIZE: 1000,
  WORLD_HALF_SIZE: 500,

  // Audio spatialization parameters
  AUDIO_MAX_PAN_SCALE: 0.45,

  // Spatial hashing configuration
  SPATIAL_GRID_CELL_SIZE: 200,

  // Physics sub-stepping and tolerances
  CCD_STEP_LIMIT_DEFAULT: 6,
  CCD_STEP_LIMIT_PROJECTILE: 5,
  GROUND_DETECTION_OFFSET: 1,
  CORNER_NUDGE_MAX_OVERLAP: 6,
  BROAD_PHASE_PADDING_STANDARD: 12,
  BROAD_PHASE_PADDING_LARGE: 24,

  // Canonical timing values (Seconds)
  ENGINE_TICK_RATE_HZ: 60,
  CANONICAL_DELTA_TIME: 1 / 60,

  // Combat range bounds
  MELEE_MAX_REACH: 76,
  MELEE_CLOSE_RANGE_THRESHOLD: 60,
  MELEE_SIDE_OFFSET: 28,
  MELEE_VERTICAL_OFFSET: 28,
  MELEE_SWEEP_INNER_RADIUS: 20,

  // Player wall jump horizontal impulse
  PLAYER_WALL_JUMP_X_VELOCITY: 1320,

  // Boss wall collision rebound velocity
  BOSS_WALL_REBOUND_VELOCITY: 280,

  // Downward attack (pogo) hitbox dimensions
  POGO_HITBOX_WIDTH: 72,
  POGO_HITBOX_HEIGHT: 35.6,
  POGO_HITBOX_Y_OFFSET: 32,
  POGO_HITBOX_X_OFFSET: -36,

  // Input Timing Buffers (Seconds)
  PLAYER_COYOTE_TIME: 0.15,
  PLAYER_JUMP_BUFFER: 0.1,
  PLAYER_WALL_COYOTE_TIME: 0.1,
  PLATFORM_COLLISION_DISABLE_TIME: 0.25,
} as const;
